# Starter pipeline
trigger:
- main

pool:
  vmImage: ubuntu-latest


#Create Infrustruture (dont forget to delete it afwards)
Stage: Create Web app to Azure
-task: AzureCLI@2
  inputs:
  azureSubscription:
  scriptType:
  script


#Build the app
Stage: Build App 


#Deploy it to app created in stage one
Stage: Deploy app to web app I created above 


Stage:
Echo: "Delete it now"