# Starter pipeline
trigger:
- main

pool:
  vmImage: ubuntu-latest


#Create Infrustruture (dont forget to delete it afwards)
Stage: Create Web app to Azure
-task: AzureCLI@2
  inputs:
  azureSubscription:
  scriptType:
  script


Stage: Build App 


Stage: Deploy app to web app I created above 
