# Pipeline I created to 1)create webapp into exisitng rg and plan

trigger:
- main

pool:
  vmImage: ubuntu-latest


stages:
- stage: CreateWebApp
  displayName: "Create Web App on Azure"
  jobs:
  - job: CreateApp
    displayName: 'Create app via CLI'
    steps:
    - task: AzureCLI@2
      displayName: "AzureCLI Deployment"
      inputs:
        azureSubscription: SPN-Dev-01 
        scriptType: bash 
        scriptLocation: inlineScript
        inlineScript: |
          az webapp create \  
          --resource-group AZ400-play \   
          --plan ASP-AzureAppIncidentProjectgroup-8d3f \   
          --name flaskappgmd28 \  
          --runtime "PYTHON:3.10"

- stage: BuildApp
  displayName: 'Build Python Stage'
  dependsOn: CreateWebApp
  isSkippable: false
  jobs:
  - job: BuildAppOnDevops
    displayName: 'Build App on Devops'
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(python.version)'
    - script: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      displayName: 'Install dependencies'

- stage: DeployApp
  displayName: 'Deploy App Stage'
  dependsOn: BuildApp
  isSkippable: false
  jobs:
  - job: DeployToAzure 
    displayName: 'Deploy Build App to Azure'
    steps:
    - task: AzureWebApp@1
      inputs:
        azureSubscription: SPN-Dev-01
        appType: webApp 
        appName: flaskappgmd28 
        package: '$(System.DefaultWorkingDirectory)'

- stage: ReminderToDelete
  displayName: 'Reminder to delete'
  dependsOn: DeployApp
  isSkippable: false
  jobs:
  - job: Reminder
    displayName: 'Text reminder '
    steps:
    - script: |
        echo "Delete or at least stop"
